### ISSUE TITLE
请问是否有在test数据集上的测试结果？

### ISSUE THREAD

**Issue by ccccj** [FlagOpen/TACO#10]
貌似测试结果的pass@1、pass@10和pass@100都是在train数据集上测的结果？（或者是train+test？）请问是否有在test数据集上单独测试过呢？

**Comment by rongaoli** [comment]
Results reported in paper was **only** on the TACO-test split.

**Comment by ccccj** [comment]
不好意思，不知道是否是我的理解有误，论文中使用的是pass@k，我理解的是，pass@1就是生成1次代码，通过的个数再除以总的问题个数，如果是只在test上测的，test split一共1000个问题，以 codellama-7b-python 的 pass@1 为例，是9.32%，通过的总个数是93.2个？为什么会有小数呢？不知道是我哪里理解错了

**Comment by rongaoli** [comment]
We compute Pass@k according to formula mentioned in Codex Paper. 
I think it will help you :)

**Comment by ccccj** [comment]
原来如此！我对这个式子的理解有些问题，感谢您~
