### ISSUE TITLE
compute_metric.py 好像有问题

### ISSUE THREAD

**Issue by Iiji** [FlagOpen/TACO#11]
我从test set里抽了20题，然后用compute_metric.py评测了一下数据集自带的solution code, 但大概只有60%-70%能通过评测。我找了一份没通过的代码，人工评估是对的，提交到Codeforces也Accepted了，所以应该是评测这块有问题。另，论文里report的结果是用这个script算出来的吗？

**Comment by rongaoli** [comment]
我们当前的评测框架是复用APPS的，我们也发现了这个问题，正在修复框架，会在近期更新

**Comment by Iiji** [comment]
谢谢，期待你们的更新！但是，一部分OI题的合法输出不是唯一的(有些题目要求是输出任意一组合法/最优解)，这种情况一般会需要一个checker script去验证输出的正确性，请问你们有计划同时解决这个问题吗？我知道这不简单，因为想要完整支持OI题的评测基本上等价于要搭一个简易OJ+给每个题写好配置文件了，不知道你们在这方面有没有什么smart solution？

**Comment by rongaoli** [comment]
> 我从test set里抽了20题，然后用compute_metric.py评测了一下数据集自带的solution code, 但大概只有60%-70%能通过评测。我找了一份没通过的代码，人工评估是对的，提交到Codeforces也Accepted了，所以应该是评测这块有问题。另，论文里report的结果是用这个script算出来的吗？

您好，我们最近解决了 [APPS](https://github.com/hendrycks/apps) 测试框架中的一些已知问题。

经过广泛的手动验证和调试，我们发布了第一个版本。在此次更新中，我们修复了APPS基准中的多个错误，重新检查了测试用例，并将 [TACO](https://huggingface.co/datasets/BAAI/TACO) 测试集更新到了最新版本。

你可以在这里找到更多详细信息：https://github.com/FlagOpen/TACO/tree/main/metrics

期待您的反馈！感谢您协助审查这一框架。

**Comment by Iiji** [comment]
更新后的评测框架似乎存在重大bug？我再次尝试评测了数据集自带的solution code，但似乎所有评测都失败了，具体表现为check_correctness()返回的所有结果都是-1。我不太了解APPS的测试框架，因此没有进一步排查，你们能够检查一下这个问题吗？
