### ISSUE TITLE
更新后的评测框架似乎存在重大bug?

### ISSUE THREAD

**Issue by Iiji** [FlagOpen/TACO#12]
我再次尝试评测了数据集自带的solution code，但似乎所有评测都失败了，check_correctness()返回的所有结果都是-1。我不太了解APPS的测试框架，因此没有进一步排查，你们能够检查一下这个问题吗？

**Comment by rongaoli** [comment]
是个小问题。可能是我们为了最少改变使用方式而引发的错误，我们本周尽快fix
