### ISSUE TITLE
How to construct the appropriate output?

### ISSUE THREAD

**Issue by QuaY316** [FlagOpen/TACO#2]
I try to evaluate codellama-7b using the easy difficulty of the TACO dataset. But I find that the output code needs to meet certain specifications in order to pass the test cases, like 
`s = input()\nprint(s.swapcase())`
not
`def solve(s):\n    return s.swapcase()`
How to construct the appropriate output?

**Comment by bowen92** [comment]
The difference is the format to use. Actually we should claim the format to use when given the question.

`s = input()\nprint(s.swapcase())` is the "Standard Input format" while the code `def solve(s):\n    return s.swapcase()` is "Call-Based format"

We double-checked our code and update the prompt in `generation.py`, please use the updated version.
Let us know if you have other problem.
