### ISSUE TITLE
题目的难度是如何确定的？/ How is the difficulty level obtained?

### ISSUE THREAD

**Issue by Happylkx** [FlagOpen/TACO#7]
请问数据集中题目难度的标注是如何确定的，是基于网站本身的标签还是用户通过率呢？

------------------

Hi, thanks for the great work! I am curious about the criteria of the difficulty level annotation in the files. Is it based on the website's own tagging or the user pass rates? Can you share more details on this? Thank you!

**Comment by Connor-Shen** [comment]
+1

**Comment by rongaoli** [comment]
Apologize for the delayed response and appreciate your interest in our project. 

Based on Codeforces, problem difficulties are arranged into five levels: Easy (Beginner) for fundamental algorithm understanding, Medium (Professional) for solid algorithmic skills, Medium-High (Expert) for advanced techniques and problem solving abilities, Hard (Advanced Expert) challenging even experienced solvers with complex algorithms, and Very Hard (Master) aimed at the elite with demands for exceptional algorithmic mastery and innovation. For problems from other sources, we systematically map their difficulty to our defined levels by carefully analyzing and normalizing their **website's own tagging**, ensuring a consistent and comparative framework across various platforms.

**Comment by rongaoli** [comment]
> 请问数据集中题目难度的标注是如何确定的，是基于网站本身的标签还是用户通过率呢？
> 
> Hi, thanks for the great work! I am curious about the criteria of the difficulty level annotation in the files. Is it based on the website's own tagging or the user pass rates? Can you share more details on this? Thank you!

Apologize for the delayed response and appreciate your interest in our project!

Based on Codeforces, problem difficulties are arranged into five levels: Easy (Beginner) for fundamental algorithm understanding, Medium (Professional) for solid algorithmic skills, Medium-High (Expert) for advanced techniques and problem solving abilities, Hard (Advanced Expert) challenging even experienced solvers with complex algorithms, and Very Hard (Master) aimed at the elite with demands for exceptional algorithmic mastery and innovation. For problems from other sources, we systematically map their difficulty to our defined levels by carefully analyzing and normalizing their website's own tagging, ensuring a consistent and comparative framework across various platforms.
